version: '3'

services:
  web:
    build: .
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8001 --workers 4
    volumes:
      - .:/code
    env_file:
    - project/.env
    ports:
      - 8001:8001
